import React,{useEffect,useRef,useState} from 'react';
import {drawCard} from './cardRenderer';
export default function CardViewer({settings,photo,media,onClose}){
 const dialog=useRef(),canvas=useRef(),[tilt,setTilt]=useState({x:0,y:0}),[flipped,setFlipped]=useState(false);
 useEffect(()=>{const el=dialog.current;el.showModal();return()=>el.close();},[]);
 useEffect(()=>{if(media)return;let raf;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const ctx=canvas.current.getContext('2d');const draw=now=>{drawCard(ctx,settings,reduced?0:(now%4000)/4000,photo);if(!reduced)raf=requestAnimationFrame(draw);};draw(performance.now());return()=>cancelAnimationFrame(raf);},[settings,photo,media]);
 const follow=e=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const b=e.currentTarget.getBoundingClientRect();setTilt({x:-(e.clientY-b.top-b.height/2)/b.height*24,y:(e.clientX-b.left-b.width/2)/b.width*30});};
 return <dialog ref={dialog} className="collectible-viewer" onCancel={onClose} aria-label="Collectible in your hands"><button autoFocus onClick={onClose}>Close collectible ×</button>{media?.type.startsWith('video')?<video src={media.url} autoPlay loop muted playsInline controls/>:media?<img src={media.url} alt="Your animated collectible"/>:<><div className="card-perspective" onPointerMove={follow} onPointerLeave={()=>setTilt({x:0,y:0})} onPointerUp={()=>setTilt({x:0,y:0})}><div className="card-object" style={{transform:`rotateX(${tilt.x}deg) rotateY(${tilt.y+(flipped?180:0)}deg)`}}><canvas width="648" height="810" ref={canvas} role="img" aria-label={`${settings.name||'Your'} collectible`}/><div className="card-reverse"><span>SEPANG 26</span><strong>{settings.mode==='prediction'?'YOU CALLED IT.':'THE WEEKEND BELONGS TO YOU.'}</strong><p>{settings.teamName||'Malaysia'} · Fan edition</p><p>5.543 km · 15 turns · One shared passion.</p><small>Independent fan souvenir. Not valid for admission.</small></div></div></div><button onClick={()=>setFlipped(v=>!v)}>{flipped?'Show front':'Turn the card'}</button></>}<p>{media?'Your downloaded file, playing here.':'Move across or drag gently to tilt · turn to see the reverse'}</p></dialog>;
}
