import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Download,Share2} from 'lucide-react';
import {SNAPSHOT,TEAM_COLORS} from './standings';

const modeLabels={going:"I'M GOING TO SEPANG",online:"I'M WATCHING ONLINE",prediction:'MY SEPANG PREDICTION'};
const teamList=SNAPSHOT.constructors.map(x=>({id:x.teamId,name:x.team,color:TEAM_COLORS[x.teamId]}));
const nameOf=d=>`${d.given} ${d.family}`;

function fit(ctx,text,max,size,min=28){ctx.font=`900 ${size}px Arial Narrow, Arial`;while(ctx.measureText(text).width>max&&size>min){size-=2;ctx.font=`900 ${size}px Arial Narrow, Arial`;}return size;}
function cardBlob(canvas){return new Promise(resolve=>canvas.toBlob(resolve,'image/png',1));}

export default function FanStudio({drivers=SNAPSHOT.drivers}){
 const canvas=useRef(null),[mode,setMode]=useState('going'),[name,setName]=useState(''),[teamId,setTeam]=useState('ferrari'),[feedback,setFeedback]=useState('');
 const [prediction,setPrediction]=useState({pole:'',p1:'',p2:'',p3:'',fastest:'',safety:'yes',rain:'yes'});
 const team=teamList.find(t=>t.id===teamId)||teamList[0];
 const complete=name.trim()&&(mode!=='prediction'||['pole','p1','p2','p3','fastest'].every(k=>prediction[k]));
 const initials=useMemo(()=>name.trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'S',[name]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d'),W=c.width,H=c.height;ctx.clearRect(0,0,W,H);ctx.fillStyle='#f1ecdf';ctx.fillRect(0,0,W,H);ctx.fillStyle='#0d1012';ctx.fillRect(0,0,W,170);ctx.fillStyle='#ef2638';ctx.fillRect(0,170,W,650);ctx.fillStyle=team.color;ctx.fillRect(0,160,W,12);ctx.fillStyle='#0d1012';ctx.fillRect(0,820,W,H-820);
  ctx.fillStyle='#f1ecdf';ctx.font='900 76px Arial Narrow, Arial';ctx.fillText('SEPANG',58,112);ctx.fillStyle='#ef2638';ctx.fillText('26',385,112);ctx.font='700 28px monospace';ctx.fillStyle='#f1ecdf';ctx.fillText('02 — 04 OCT 2026',690,75);ctx.font='700 22px monospace';ctx.fillText('BAHRAIN GRAND PRIX IN MALAYSIA',690,115);
  ctx.globalAlpha=.12;ctx.fillStyle='#000';ctx.font='900 620px Georgia';ctx.fillText(initials[0],38,745);ctx.globalAlpha=1;ctx.fillStyle='#f1ecdf';ctx.textAlign='center';ctx.font='900 420px Georgia';ctx.fillText(initials,540,660);ctx.font=`900 ${fit(ctx,name.trim().toUpperCase()||'YOUR NAME',900,74)}px Arial Narrow, Arial`;ctx.fillText(name.trim().toUpperCase()||'YOUR NAME',540,770);ctx.textAlign='left';ctx.fillStyle=team.color;ctx.fillRect(58,858,18,120);ctx.fillStyle='#f1ecdf';ctx.font='900 34px Arial';ctx.fillText(modeLabels[mode],100,890);ctx.font='700 25px monospace';ctx.fillText(team.name.toUpperCase(),100,935);
  if(mode==='prediction'){ctx.font='700 20px monospace';const find=id=>nameOf(drivers.find(d=>d.code===id)||{given:'—',family:''});const lines=[`POLE  ${find(prediction.pole)}`,`PODIUM  ${find(prediction.p1)} / ${find(prediction.p2)} / ${find(prediction.p3)}`,`FASTEST  ${find(prediction.fastest)}`,`SAFETY CAR  ${prediction.safety.toUpperCase()}     RAIN  ${prediction.rain.toUpperCase()}`];lines.forEach((l,i)=>ctx.fillText(l,100,1000+i*42));}else{ctx.font='700 24px monospace';ctx.fillText(mode==='going'?'SEE YOU AT SEPANG INTERNATIONAL CIRCUIT':'FOLLOWING EVERY LAP, WHEREVER I AM',100,1010);ctx.fillText('5.543 KM · 15 TURNS · 56 LAPS',100,1060);}
  ctx.strokeStyle='#f1ecdf';ctx.globalAlpha=.45;ctx.setLineDash([10,10]);ctx.beginPath();ctx.moveTo(58,1180);ctx.lineTo(1022,1180);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;ctx.font='700 19px monospace';ctx.fillText('SEPANG INTERNATIONAL CIRCUIT · MALAYSIA',58,1240);ctx.fillText('SAME HEAT. HIGHER STAKES.',58,1280);
 },[mode,name,team,prediction,drivers,initials]);
 const getFile=async()=>new File([await cardBlob(canvas.current)],`sepang26-${mode}-${name.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-')}.png`,{type:'image/png'});
 const download=async()=>{if(!complete)return;const file=await getFile(),a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);setFeedback('PNG downloaded.');};
 const share=async()=>{if(!complete)return;const file=await getFile();if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'My Sepang 26 fan card',files:[file]});setFeedback('Card shared.');}else{await download();setFeedback('Sharing is not supported here, so the PNG was downloaded.');}};
 const options=<><option value="">Choose driver</option>{drivers.map(d=><option key={d.code} value={d.code}>{nameOf(d)} · {d.team}</option>)}</>;
 return <section id="fan-card" className="fan-studio"><div className="studio-copy"><h2>Put your name on race weekend.</h2><div className="mode-tabs">{Object.entries(modeLabels).map(([k,v])=><button className={mode===k?'active':''} key={k} onClick={()=>{setMode(k);setFeedback('')}}>{k==='going'?"I'm Going":k==='online'?'Watching Online':'My Prediction'}</button>)}</div><div className="studio-form"><label>Name<input value={name} maxLength={28} placeholder="Your name" onChange={e=>setName(e.target.value)}/><small>Initials are generated automatically.</small></label><fieldset><legend>Choose team</legend><div className="team-picker">{teamList.map(t=><button type="button" title={t.name} aria-label={t.name} aria-pressed={teamId===t.id} className={teamId===t.id?'active':''} key={t.id} onClick={()=>setTeam(t.id)} style={{'--swatch':t.color}}><span/>{t.name}</button>)}</div></fieldset>{mode==='prediction'&&<div className="prediction-grid"><label>Pole winner<select value={prediction.pole} onChange={e=>setPrediction({...prediction,pole:e.target.value})}>{options}</select></label><label>Podium P1<select value={prediction.p1} onChange={e=>setPrediction({...prediction,p1:e.target.value})}>{options}</select></label><label>Podium P2<select value={prediction.p2} onChange={e=>setPrediction({...prediction,p2:e.target.value})}>{options}</select></label><label>Podium P3<select value={prediction.p3} onChange={e=>setPrediction({...prediction,p3:e.target.value})}>{options}</select></label><label>Fastest lap<select value={prediction.fastest} onChange={e=>setPrediction({...prediction,fastest:e.target.value})}>{options}</select></label><label>Safety car<select value={prediction.safety} onChange={e=>setPrediction({...prediction,safety:e.target.value})}><option value="yes">Yes</option><option value="no">No</option></select></label><label>Rain<select value={prediction.rain} onChange={e=>setPrediction({...prediction,rain:e.target.value})}><option value="yes">Yes</option><option value="no">No</option></select></label></div>}<div className="export-actions"><button disabled={!complete} onClick={share}><Share2/>Share card</button><button className="primary" disabled={!complete} onClick={download}><Download/>Download PNG</button></div>{!complete&&<p className="form-hint">{!name.trim()?'Add your name to unlock the card.':'Complete every driver prediction to export.'}</p>}{feedback&&<p className="success" role="status">{feedback}</p>}</div></div><div className="card-preview"><canvas ref={canvas} width="1080" height="1350" aria-label="Live preview of your Sepang 26 fan card"/></div></section>
}
