import React,{useEffect,useRef,useState} from 'react';
import useSaved from './useSaved';
import {OFFICIAL,ANNOUNCEMENT,TICKETS} from './data';
import './history.css';

const memories='https://www.formula1.com/en/latest/article/watch-kimis-maiden-win-and-9-other-malaysian-moments.MfJ5DYiP4i2jvRS2u2LCi';
const events=[
 {year:'1997–1999',title:'A new home for Malaysian motorsport',intro:'From construction to Formula 1’s first Sepang weekend.',paragraphs:['Construction began in 1997, with Hermann Tilke designing a purpose-built circuit that opened in 1999. Sepang combined wide track surfaces, long straights and fast corners in a layout shaped for modern Grand Prix racing.','The inaugural Malaysian Grand Prix was won by Eddie Irvine. Michael Schumacher returned from injury and supported his Ferrari teammate’s championship campaign. Malaysia’s debut immediately became part of the title story.'],source:OFFICIAL,label:'Formula 1 · circuit origins and inaugural race'},
 {year:'2003',title:'The Iceman’s first victory',intro:'Kimi Räikkönen converts seventh on the grid into a breakthrough win.',paragraphs:['Räikkönen earned his first Grand Prix victory at Sepang for McLaren, starting seventh. It was an early landmark in the career of a future world champion.','Formula 1’s retrospective recalls Ron Dennis describing a faultless drive and the importance of a driver securing that first win.'],source:memories,label:'Formula 1 · Malaysian moments'},
 {year:'2009',title:'When the rain stopped the race',intro:'Button wins a shortened Grand Prix worth half points.',paragraphs:['Torrential rain ended the race early. Jenson Button was declared the winner for Brawn, but the shortened distance meant half points were awarded under the rules in force that year.','Button received five points, while Nico Rosberg received half a point for eighth. The classification was taken at the end of lap 31. Sepang’s weather had changed both the spectacle and its championship reward.'],source:'https://www.formula1.com/en/latest/article/f1-malaysia-grand-prix-in-numbers.2maUcmzDITGF9f6dkAuQh',label:'Formula 1 · Malaysian Grand Prix in numbers'},
 {year:'2012',title:'Alonso versus an unlikely challenger',intro:'Sergio Pérez puts Sauber in the fight for victory.',paragraphs:['A disrupted, changeable-weather race ended with Fernando Alonso winning from eighth on the grid. Sergio Pérez challenged him in the Sauber and finished second.','Pérez’s charge became the defining contest of the afternoon. He later described touching a wet kerb while hunting Alonso, a reminder of how narrow the margin was between an attack and a costly mistake.'],source:memories,label:'Formula 1 · Alonso and Pérez retrospective'},
 {year:'2013',title:'“Multi 21” splits Red Bull',intro:'A team-order dispute overshadows Vettel’s victory.',paragraphs:['Red Bull instructed Sebastian Vettel to remain behind Mark Webber. Vettel instead attacked and passed his teammate for the lead.','The tense battle continued into the post-race discussion: Vettel acknowledged a mistake, while Webber made his frustration clear. Sepang became shorthand for one of Formula 1’s best-known team-order disputes.'],source:memories,label:'Formula 1 · the Multi 21 dispute'},
 {year:'2016',title:'A title fight changes in smoke',intro:'Hamilton retires; Ricciardo leads a Red Bull one-two.',paragraphs:['Lewis Hamilton’s engine failed on lap 41. Daniel Ricciardo won ahead of Max Verstappen, with Nico Rosberg finishing third.','The championship impact extended beyond the lost win. Rosberg’s third place put him 23 points ahead of Hamilton with five races remaining. Formula 1’s season review identifies Sepang as a major blow to Hamilton’s title hopes.'],source:'https://www.formula1.com/en/latest/article/f1-2016-season-review-rosberg-hamilton.15Y7Aq2tzCVCnsWKgt4xxT',label:'Formula 1 · 2016 season review'},
 {year:'2017',title:'Verstappen wins the farewell',intro:'A second career victory, one day after his twentieth birthday.',paragraphs:['Max Verstappen won the final Malaysian Grand Prix of Sepang’s original run. Lewis Hamilton finished second and Daniel Ricciardo third, giving Red Bull two drivers on the podium.','It was Verstappen’s second career win. Sebastian Vettel recovered from last on the grid to fourth and set the fastest lap. Across 19 Sepang races, Formula 1 recorded 11 different winners—a fitting measure of the venue’s variety.'],source:'https://www.formula1.com/en/latest/article/malaysia-red-bull-secure-first-podium-double-for-a-year.3iyPb5jhS0Cu6MOAMWiAuu',label:'Formula 1 · 2017 farewell race statistics'},
 {year:'2026',title:'Bahrain’s round, Malaysia’s stage',intro:'Why the event returns with a different Grand Prix name.',paragraphs:['The July announcement described an agreement involving Formula 1, the FIA and the governments of Bahrain and Malaysia. Its stated purpose was to preserve a Grand Prix that otherwise would not have taken place.','Sepang is the host venue, while Bahrain’s name remains on the event. The announcement specified 2–4 October and included a final-agreements and approval caveat. The official event page now carries the weekend schedule; consult it for subsequent changes.'],source:ANNOUNCEMENT,label:'Formula 1 · return announcement',extra:OFFICIAL}
];

const context=[
 ['A circuit has to become more than a line on a calendar. Its first race gives fans something to attach to the concrete: a comeback, a result, a championship argument. Sepang received all three at once. For a newcomer, that is the useful way into 1999. The new venue was immediately connected to the familiar personalities and pressures of Formula 1.', 'The Ferrari story also introduces an idea that will recur through these chapters: two cars can belong to one team without having identical priorities. Follow the drivers individually, then look at what their results mean together. That second view is often where the real story lives.'],
 ['A first victory changes how a driver’s career is read. Promising performances become evidence of something already achieved. For a fan arriving through the later legend of the Iceman, this weekend offers an earlier frame: the moment the first win finally becomes part of the record.', 'Starting position and finishing position tell different stories. Seventh on the grid is a starting condition, not a prediction of the result. When revisiting a race, keep both numbers in mind. Qualifying tells you who began with track position; the Sunday classification tells you who turned the whole weekend into a result.'],
 ['Rain changes the questions a race asks. Being quick is no longer the only consideration: drivers must be able to see, cars must remain controllable, and the circuit must be safe enough for competition. A red flag interrupts the contest because continuing is no longer simply a sporting decision.', 'This is why a rain icon on a forecast should never be read as a promise of an exciting wet race. A forecast describes a possibility over an area and a period. Race control responds to the conditions that actually exist. The distinction matters to anyone watching Sepang, a venue whose weather is woven into its identity.'],
 ['The fascination of an underdog challenge is the gap between expectation and opportunity. Fans begin with an idea of which teams should fight for victory. A race can then force them to revise that picture. The result matters, but so does the period when an unexpected challenger makes the leader’s position feel uncertain.', 'When watching a pursuit, the gap alone is only part of the drama. The following driver must get close enough to attack while keeping enough performance to complete the move. An error can arrive at the very moment an opportunity appears. That tension makes this a useful chapter for understanding why a second-place finish can remain a defining memory.'],
 ['Team orders expose a tension built into Formula 1. Drivers compete for individual results while sharing a team’s cars, resources and objectives. What is best for the constructor can conflict with what a driver wants at that exact moment. The radio may carry a short instruction; its consequences can be much larger.', 'The sporting question and the human question are different. Who won is settled by the classification. Whether teammates trust one another afterwards is harder to reduce to a number. Read this chapter with both questions in mind, and the significance of a late-race pass becomes clearer.'],
 ['A championship is assembled from results, but remembered through turning points. Mechanical failure can connect those two views brutally: one car stops, one classification changes, and the points gap takes on a new shape. Sepang is a reminder that an apparently strong race position is never the same thing as a completed result.', 'For a new fan, follow the points after the podium ceremony as carefully as the order at the finish. The race winner and the driver who gains most in the championship story are not always the same person. That is part of what makes a season rewarding to follow beyond a single Sunday.'],
 ['Farewell races invite a wider view. There is the immediate contest, with its own winner and recovery drives, and there is the longer relationship between a venue and the fans who have returned to it. A final classification closes the race; it cannot quite close the memories attached to a circuit.', 'Verstappen’s victory and Vettel’s recovery offer two different ways to watch the same afternoon. One follows the fight at the front. The other follows progress through the field. Try switching between those perspectives when revisiting a race, rather than treating the winner as the only story worth following.'],
 ['A familiar track and an unfamiliar event title can make a returning race confusing. Separate the location from the name: the venue describes where the cars race, while the event title identifies the round. That distinction helps make sense of the official schedule and the wording on this fan companion.', 'A comeback is also a practical planning exercise. Historic photographs and race memories can explain why a circuit matters, but they cannot confirm this year’s entry gates or transport arrangements. Use the archive to understand Sepang, then use the current organiser information to prepare for your own weekend.']
];
function ChapterReader({index,onChange,onClose}){const dialog=useRef(),body=useRef();const e=events[index];useEffect(()=>{const el=dialog.current;el.showModal();return()=>el.close();},[]);useEffect(()=>{body.current.scrollTop=0;},[index]);return <dialog ref={dialog} className="chapter-dialog" onCancel={onClose} aria-label="Sepang history reader"><div className="chapter-toolbar"><span>THE SEPANG ARCHIVE · {index+1} / {events.length}</span><button autoFocus onClick={onClose}>Close ×</button></div><article ref={body} className="chapter-body"><div className="chapter-cover"><span>{e.year}</span><p>CHAPTER {String(index+1).padStart(2,'0')}</p><h2>{e.title}</h2><p>{e.intro}</p></div>{e.year==='2017'&&<figure className="archive-photo"><img src="https://media.formula1.com/image/upload/t_16by9South/c_lfill%2Cw_3392/q_auto/v1740000001/fom-website/2026/Miscellaneous/GettyImages-2231479297.webp" alt="Marcus Ericsson racing the Sauber C36 at Sepang in 2017"/><figcaption>Sepang, 1 October 2017 · Formula 1 archive</figcaption></figure>}<div className="chapter-prose"><h3>The story</h3>{e.paragraphs.map(p=><p key={p}>{p}</p>)}<h3>Why it stays with us</h3>{context[index].map(p=><p key={p}>{p}</p>)}<aside>Archive facts are drawn from the reporting below. “Why it stays with us” is our editorial explanation.</aside><a href={e.source} target="_blank" rel="noreferrer">Read the original Formula 1 reporting ↗</a>{e.extra&&<a href={e.extra} target="_blank" rel="noreferrer">Current official event details ↗</a>}</div></article><nav className="chapter-pagination" aria-label="History chapters"><button disabled={index===0} onClick={()=>onChange(index-1)}>← Previous chapter</button><span>{e.year}</span><button disabled={index===events.length-1} onClick={()=>onChange(index+1)}>Next chapter →</button></nav></dialog>;}
export default function HistoryTimeline(){const [last,setLast]=useSaved('history-chapter',0,v=>Number.isInteger(v)&&v>=0&&v<events.length),[opened,setOpened]=useState(false);return <section id="story" className="history-section"><div className="section-heading"><div><span className="eyebrow">THE SEPANG ARCHIVE</span><h2>Some races stay with you.</h2></div><p>Comebacks, downpours and the moments that became folklore.</p></div><button className="outline-action" onClick={()=>setOpened(true)}>Continue reading · {events[last].year}</button><div className="archive-grid">{events.map((e,i)=><button className="archive-cover" key={e.year} onClick={()=>{setLast(i);setOpened(true);}}><span>{e.year}</span><small>CHAPTER {String(i+1).padStart(2,'0')}</small><strong>{e.title}</strong><p>{e.intro}</p><b>Read the chapter ↗</b></button>)}</div>{opened&&<ChapterReader index={last} onChange={setLast} onClose={()=>setOpened(false)}/>}</section>;}
