import React from 'react';
import {OFFICIAL,ANNOUNCEMENT,TICKETS} from './data';
import './history.css';

const memories='https://www.formula1.com/en/latest/article/watch-kimis-maiden-win-and-9-other-malaysian-moments.MfJ5DYiP4i2jvRS2u2LCi';
const events=[
 {year:'1997–1999',title:'A new home for Malaysian motorsport',intro:'From construction to Formula 1’s first Sepang weekend.',paragraphs:['Construction began in 1997, with Hermann Tilke designing a purpose-built circuit that opened in 1999. Sepang combined wide track surfaces, long straights and fast corners in a layout shaped for modern Grand Prix racing.','The inaugural Malaysian Grand Prix was won by Eddie Irvine. Michael Schumacher returned from injury and supported his Ferrari teammate’s championship campaign. Malaysia’s debut immediately became part of the title story.'],source:OFFICIAL,label:'Formula 1 · circuit origins and inaugural race'},
 {year:'2003',title:'The Iceman’s first victory',intro:'Kimi Räikkönen converts seventh on the grid into a breakthrough win.',paragraphs:['Räikkönen earned his first Grand Prix victory at Sepang for McLaren, starting seventh. It was an early landmark in the career of a future world champion.','Formula 1’s retrospective recalls Ron Dennis describing a faultless drive and the importance of a driver securing that first win.'],source:memories,label:'Formula 1 · Malaysian moments'},
 {year:'2009',title:'When the rain stopped the race',intro:'Button wins a shortened Grand Prix worth half points.',paragraphs:['Torrential rain ended the race early. Jenson Button was declared the winner for Brawn, but the shortened distance meant half points were awarded under the rules in force that year.','Button received five points, while Nico Rosberg received half a point for eighth. The classification was taken at the end of lap 31. Sepang’s weather had changed both the spectacle and its championship reward.'],source:'https://www.formula1.com/en/latest/article/f1-malaysia-grand-prix-in-numbers.2maUcmzDITGF9f6dkAuQh',label:'Formula 1 · Malaysian Grand Prix in numbers'},
 {year:'2012',title:'Alonso versus an unlikely challenger',intro:'Sergio Pérez puts Sauber in the fight for victory.',paragraphs:['A disrupted, changeable-weather race ended with Fernando Alonso winning from eighth on the grid. Sergio Pérez challenged him in the Sauber and finished second.','Pérez’s charge became the defining contest of the afternoon. He later described touching a wet kerb while hunting Alonso, a reminder of how narrow the margin was between an attack and a costly mistake.'],source:memories,label:'Formula 1 · Alonso and Pérez retrospective'},
 {year:'2013',title:'“Multi 21” splits Red Bull',intro:'A team-order dispute overshadows Vettel’s victory.',paragraphs:['Red Bull instructed Sebastian Vettel to remain behind Mark Webber. Vettel instead attacked and passed his teammate for the lead.','The tense battle continued into the post-race discussion: Vettel acknowledged a mistake, while Webber made his frustration clear. Sepang became shorthand for one of Formula 1’s best-known team-order disputes.'],source:memories,label:'Formula 1 · the Multi 21 dispute'},
 {year:'2016',title:'A title fight changes in smoke',intro:'Hamilton retires; Ricciardo leads a Red Bull one-two.',paragraphs:['Lewis Hamilton’s engine failed on lap 41. Daniel Ricciardo won ahead of Max Verstappen, with Nico Rosberg finishing third.','The championship impact extended beyond the lost win. Rosberg’s third place put him 23 points ahead of Hamilton with five races remaining. Formula 1’s season review identifies Sepang as a major blow to Hamilton’s title hopes.'],source:'https://www.formula1.com/en/latest/article/f1-2016-season-review-rosberg-hamilton.15Y7Aq2tzCVCnsWKgt4xxT',label:'Formula 1 · 2016 season review'},
 {year:'2017',title:'Verstappen wins the farewell',intro:'A second career victory, one day after his twentieth birthday.',paragraphs:['Max Verstappen won the final Malaysian Grand Prix of Sepang’s original run. Lewis Hamilton finished second and Daniel Ricciardo third, giving Red Bull two drivers on the podium.','It was Verstappen’s second career win. Sebastian Vettel recovered from last on the grid to fourth and set the fastest lap. Across 19 Sepang races, Formula 1 recorded 11 different winners—a fitting measure of the venue’s variety.'],source:'https://www.formula1.com/en/latest/article/malaysia-red-bull-secure-first-podium-double-for-a-year.3iyPb5jhS0Cu6MOAMWiAuu',label:'Formula 1 · 2017 farewell race statistics'},
 {year:'2026',title:'Bahrain’s round, Malaysia’s stage',intro:'Why the event returns with a different Grand Prix name.',paragraphs:['The July announcement described an agreement involving Formula 1, the FIA and the governments of Bahrain and Malaysia. Its stated purpose was to preserve a Grand Prix that otherwise would not have taken place.','Sepang is the host venue, while Bahrain’s name remains on the event. The announcement specified 2–4 October and included a final-agreements and approval caveat. The official event page now carries the weekend schedule; consult it for subsequent changes.'],source:ANNOUNCEMENT,label:'Formula 1 · return announcement',extra:OFFICIAL}
];

export default function HistoryTimeline(){return <section id="story" className="history-section"><div className="section-heading"><h2>Sepang, chapter by chapter.</h2><p>Open a year to explore the race, the turning point and the original reporting.</p></div><ol className="history-rail">{events.map(e=><li key={e.year}><details><summary><span className="history-year">{e.year}</span><span className="history-title"><strong>{e.title}</strong><span>{e.intro}</span></span><span className="history-toggle" aria-hidden="true">+</span></summary><div className="history-reading">{e.paragraphs.map(p=><p key={p}>{p}</p>)}<div className="history-sources"><a href={e.source} target="_blank" rel="noreferrer">{e.label} ↗</a>{e.extra&&<a href={e.extra} target="_blank" rel="noreferrer">Current official event page ↗</a>}</div></div></details></li>)}</ol><a className="history-ticket" href={TICKETS} target="_blank" rel="noreferrer">Official 2026 ticket announcement ↗</a></section>}
