import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{CloudRain,Sun,MapPin,Car,Train,Ticket,Check,ChevronRight,ShieldPlus,Navigation,CloudSun,Clock3,Umbrella,Headphones,BatteryCharging,ShieldCheck}from'lucide-react';
import'./style.css';

const days={
  Fri:[['Practice 1','10:30–11:30'],['Practice 2','14:00–15:00']],
  Sat:[['Practice 3','11:30–12:30'],['Qualifying','15:00–16:00']],
  Sun:[['Drivers’ parade','13:00'],['Race','15:00']]
};
const zones={
  main:{name:'Main Grandstand',tag:'Best all-rounder',desc:'Start, pit lane and podium in one view.',tips:['Covered seating','Closest to fan zone','Gate 1 / P1 parking']},
  k1:{name:'K1 Grandstand',tag:'Best for overtakes',desc:'Heavy braking into the opening complex.',tips:['Morning sun exposure','Bring binoculars','Gate 2 / P2 parking']},
  c2:{name:'C2 Hillstand',tag:'Best value',desc:'Wide view across the final sector.',tips:['Open-air grass bank','Poncho essential','Gate 3 / P3 parking']}
};
const checks=[['ticket','Digital ticket',Ticket],['poncho','Rain poncho',Umbrella],['power','Power bank',BatteryCharging],['sun','Sunscreen',Sun],['ears','Ear protection',Headphones]];

function Weather(){return <section className="weather section"><div><p className="section-title">Sepang weather & strategy</p><h2>Prepare for both races.</h2><p className="muted">Planning scenario based on Sepang’s tropical climate. Recheck the forecast before departure.</p></div><div className="metrics"><div><Sun/><b>32°C</b><small>Hot</small></div><div><CloudSun/><b>78%</b><small>Humidity</small></div><div><CloudRain/><b>70%</b><small>Rain risk</small></div></div><div className="strategy"><span>DRY</span><i/><ChevronRight/><span>SHOWERS</span><i className="green"/><ChevronRight/><span>WET</span></div></section>}

function Circuit(){const[z,setZ]=useState('main'),d=zones[z];return <section className="circuit section" id="circuit"><div className="section-head"><div><p className="section-title">Explore the circuit</p><h2>Pick the right view.</h2></div><span>5.543 KM · 15 TURNS</span></div><div className="circuit-grid"><div className="track-wrap"><svg viewBox="0 0 500 260" aria-label="Stylised Sepang circuit map"><path className="track-shadow" d="M66 184 C30 145 67 101 124 109 C164 115 157 44 211 43 C267 43 247 117 305 105 C337 98 335 45 389 59 C465 79 454 158 397 165 C344 172 328 224 267 209 C229 199 213 159 169 174 C129 188 103 219 66 184Z"/><path className="track" d="M66 184 C30 145 67 101 124 109 C164 115 157 44 211 43 C267 43 247 117 305 105 C337 98 335 45 389 59 C465 79 454 158 397 165 C344 172 328 224 267 209 C229 199 213 159 169 174 C129 188 103 219 66 184Z"/>{[['main',270,210],['k1',394,60],['c2',72,188]].map(([id,x,y])=><g key={id} onClick={()=>setZ(id)} className={'marker '+(z===id?'active':'')}><circle cx={x} cy={y} r="10"/><text x={x+16} y={y+5}>{zones[id].name}</text></g>)}</svg></div><div className="zone-detail"><div><span className="tag">{d.tag}</span><h3>{d.name}</h3><p>{d.desc}</p></div><ul>{d.tips.map(x=><li key={x}><Check/>{x}</li>)}</ul><div className="zone-tabs">{Object.entries(zones).map(([id,v])=><button onClick={()=>setZ(id)} className={z===id?'selected':''} key={id}>{v.name}</button>)}</div></div></div></section>}

function Planner(){const[from,setFrom]=useState('KL city centre'),[mode,setMode]=useState('car'),[done,setDone]=useState(false);return <section className="planner section" id="plan"><div><p className="section-title">Arrival planner</p><h2>Beat the race-day queue.</h2><p className="muted">Set your starting point and we’ll recommend a safe buffer.</p></div><div className="planner-controls"><label>Leaving from<select value={from} onChange={e=>setFrom(e.target.value)}><option>KL city centre</option><option>Petaling Jaya</option><option>Putrajaya</option><option>KLIA</option></select></label><div className="mode"><button className={mode==='car'?'selected':''} onClick={()=>setMode('car')}><Car/>Drive</button><button className={mode==='train'?'selected':''} onClick={()=>setMode('train')}><Train/>Train + shuttle</button></div><button className="primary" onClick={()=>setDone(true)}>Build my arrival plan <ChevronRight/></button></div><div className={'plan-result '+(done?'show':'')}><Clock3/><div><small>RECOMMENDED DEPARTURE</small><strong>{mode==='car'?'7:00 AM':'7:20 AM'}</strong><p>{mode==='car'?`${from} → ELITE Highway → P1 → Gate 1`:`${from} → KL Sentral → KLIA Transit → shuttle`}</p></div><Navigation/></div></section>}

function Checklist(){const[ready,setReady]=useState(()=>JSON.parse(localStorage.getItem('sepang-ready')||'["ticket"]'));useEffect(()=>localStorage.setItem('sepang-ready',JSON.stringify(ready)),[ready]);const toggle=id=>setReady(r=>r.includes(id)?r.filter(x=>x!==id):[...r,id]);return <section className="checklist section"><div className="section-head"><div><p className="section-title">Your race-weekend kit</p><h2>{ready.length} of {checks.length} ready</h2></div><div className="progress"><i style={{width:`${ready.length/checks.length*100}%`}}/></div></div><div className="check-row">{checks.map(([id,label,Icon])=><button key={id} className={ready.includes(id)?'checked':''} onClick={()=>toggle(id)}><span>{ready.includes(id)?<Check/>:<Icon/>}</span><b>{label}</b><small>{ready.includes(id)?'Packed':'Tap when packed'}</small></button>)}</div></section>}

function App(){const[day,setDay]=useState('Fri');return <><header><a className="brand" href="#top"><strong>SEPANG</strong><span>RACE HUB</span></a><nav><a className="active" href="#top">Today</a><a href="#circuit">Circuit</a><a href="#plan">Plan</a></nav><div className="date">2–4 OCT 2026<br/><small>SEPANG, MALAYSIA</small></div></header><main id="top"><section className="hero"><div className="hero-copy"><p>Formula 1 Gulf Air Bahrain Grand Prix in Malaysia</p><h1>Race weekend<br/>starts in <em>27 days</em></h1><div className="hero-action"><Clock3/><span><small>NEXT FOR YOU</small><b>Plan your Friday arrival</b></span><a href="#plan"><ChevronRight/></a></div></div></section><section className="schedule section"><div className="day-tabs">{Object.keys(days).map((d,i)=><button key={d} onClick={()=>setDay(d)} className={day===d?'selected':''}><b>{d.toUpperCase()}</b><span>{i+2} OCT</span></button>)}</div><div className="sessions">{days[day].map(([name,time],i)=><div key={name}><span>0{i+1}</span><p>{name}</p><strong>{time}</strong></div>)}</div><div className="local"><MapPin/> Times shown in Malaysia Time (MYT)</div></section><Weather/><Circuit/><Planner/><Checklist/><footer><div><ShieldPlus/><span><b>Need help?</b><small>Emergency 999 · Medical centre at main concourse</small></span></div><a href="https://www.sepangcircuit.com/home" target="_blank">Official circuit information <ChevronRight/></a></footer></main></>}

createRoot(document.getElementById('root')).render(<App/>);
