import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {CloudRain,RefreshCw,ExternalLink,CalendarDays,MapPin} from 'lucide-react';
import CircuitMap from './CircuitMap';
import useFeed from './useFeed';
import {OFFICIAL,CIRCUIT,ANNOUNCEMENT,TICKETS,VERIFIED,sessions,dateMY,timeMY,FORECAST,WARNINGS,forecastRows,activeWarnings,describe} from './data';
import './style.css';
const External=({href,children})=><a href={href} target="_blank" rel="noreferrer">{children} <ExternalLink size={14}/></a>;
function Weather(){
 const feed=useFeed(FORECAST,forecastRows),warnings=useFeed(WARNINGS,activeWarnings);
 const [selected,setSelected]=useState('');const row=feed.rows.find(r=>r.date===selected)||feed.rows[0];
 return <section id="weather"><div className="section-head"><div><p className="eyeline">MET Malaysia via data.gov.my</p><h2>Sepang district forecast</h2></div><button onClick={()=>{feed.refresh();warnings.refresh();}} disabled={feed.loading||warnings.loading}><RefreshCw size={16}/>{feed.loading?'Refreshing…':'Refresh'}</button></div><p>Official daily forecast—not a trackside observation. Checks for updates every five minutes while this page is visible.</p>
 {feed.error&&<p className="notice error" role="alert">{feed.error} {feed.retrieved?'Last retrieved data below may be stale.':'Forecast unavailable. No sample data is substituted.'}</p>}
 {feed.loading&&!feed.retrieved&&<p role="status">Contacting data.gov.my…</p>}
 {!!feed.rows.length&&<><div className="forecast-tabs" aria-label="Forecast date">{feed.rows.map(r=><button aria-pressed={row.date===r.date} className={row.date===r.date?'selected':''} key={r.date} onClick={()=>setSelected(r.date)}>{new Date(r.date+'T12:00:00+08:00').toLocaleDateString('en-GB',{timeZone:'Asia/Kuala_Lumpur',weekday:'short',day:'numeric',month:'short'})}</button>)}</div><div className="weather-readout"><div><CloudRain size={36}/><h3>{describe(row.summary_forecast)}</h3><strong>{Number.isFinite(row.min_temp)?row.min_temp:'—'}–{Number.isFinite(row.max_temp)?row.max_temp:'—'}°C</strong><p>Forecast daily low / high · {row.date}</p></div><dl>{[['Morning',row.morning_forecast],['Afternoon',row.afternoon_forecast],['Night',row.night_forecast]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{describe(value)}<small lang="ms">{value}</small></dd></div>)}</dl></div></>}
 {!feed.loading&&!feed.error&&!feed.rows.length&&<p className="notice">No current Sepang district forecast returned.</p>}
 <div className="notice"><b>Race weekend · 2–4 October</b><p>{feed.rows.some(r=>r.date>='2026-10-02'&&r.date<='2026-10-04')?'Available race-weekend dates appear above. Missing dates are not yet available.':'Race-weekend forecast not available yet. Dates appear automatically when MET Malaysia publishes them.'}</p></div><p className="meta">{feed.retrieved?`Retrieved ${timeMY(feed.retrieved)} MYT, ${dateMY(new Date(feed.retrieved))}.`:'No successful retrieval yet.'} Forecasts update daily. Humidity, rain percentages and live track conditions are not supplied.</p><External href="https://developer.data.gov.my/realtime-api/weather">Source and update frequency</External>
 <div className="warnings"><h3>Weather warnings · Selangor / Sepang</h3><p className="meta">Active bulletins mentioning Sepang or Selangor. State-wide matches may not apply to the circuit; read the affected areas.</p>{warnings.error?<p role="alert">Warning feed unavailable: {warnings.error} Check MET Malaysia directly.</p>:warnings.loading&&!warnings.retrieved?<p>Checking official warnings…</p>:warnings.rows.length?warnings.rows.map((w,i)=><article key={i} className="notice"><h4>{w.heading_en||w.heading_bm}</h4><p>{w.text_en||w.text_bm}</p><p>{w.instruction_en||w.instruction_bm}</p><small>Valid until {w.valid_to} MYT</small></article>):<p>No matching active warning returned. This is not an all-clear or a guarantee of safe conditions.</p>}<External href="https://www.met.gov.my/">Check MET Malaysia</External></div></section>;
}
function Schedule({now}){const [day,setDay]=useState('2026-10-02');const rows=sessions.filter(s=>s.start.startsWith(day));
 const calendar=()=>{const utc=s=>s.replace(/[-:]/g,'');const body=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Sepang Race Hub//EN',...sessions.flatMap(s=>['BEGIN:VEVENT',`UID:sepang2026-${s.start}@racehub`,`DTSTAMP:${utc(new Date().toISOString().replace(/\.\d+Z$/,'Z'))}`,`DTSTART:${utc(s.start)}`,`DTEND:${utc(s.end)}`,`SUMMARY:Sepang F1 - ${s.name}`,'LOCATION:Sepang International Circuit',`DESCRIPTION:Official F1 schedule checked ${VERIFIED}. Recheck ${OFFICIAL}`,'END:VEVENT']),'END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([body],{type:'text/calendar'}));const a=document.createElement('a');a.href=url;a.download='SepangF1-2026.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section id="schedule"><div className="section-head"><div><p className="eyeline">Official F1 schedule</p><h2>Your weekend, Malaysian time.</h2></div><button onClick={calendar}><CalendarDays size={16}/>Save calendar</button></div><div className="day-tabs">{['02','03','04'].map((n,i)=><button key={n} className={day.endsWith(n)?'selected':''} aria-pressed={day.endsWith(n)} onClick={()=>setDay('2026-10-'+n)}>{['Friday','Saturday','Sunday'][i]} <b>{n} OCT</b></button>)}</div><div className="sessions">{rows.map(s=><article key={s.name}><div><h3>{s.name}</h3><small>{now>=Date.parse(s.end)?'Scheduled time elapsed':now>=Date.parse(s.start)?'Within scheduled window · not live timing':'Upcoming'}</small></div><strong>{timeMY(s.start)}{s.name==='Race'?'':`–${timeMY(s.end)}`}</strong></article>)}</div><p className="meta">MYT · UTC+8. Official timetable verified {VERIFIED}; subject to changes. Calendar uses scheduled end times, not guaranteed durations. Not a live timing feed.</p><External href={OFFICIAL}>Latest official timetable and results</External></section>;
}
function Plan(){const [origin,setOrigin]=useState(''),[mode,setMode]=useState('driving');const params=new URLSearchParams({api:'1',destination:'Sepang International Circuit, Malaysia',travelmode:mode});if(origin.trim())params.set('origin',origin.trim());return <section id="plan"><p className="eyeline">Getting to the circuit</p><h2>Real directions. No invented ETA.</h2><p>Jalan Pekeliling, 64000 KLIA, Selangor, Malaysia. Google Maps supplies routes and available travel options when you open directions.</p><div className="route-form"><label>Starting point<input value={origin} onChange={e=>setOrigin(e.target.value)} placeholder="E.g. KL Sentral or your hotel"/></label><label>Travel mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="driving">Driving</option><option value="transit">Public transport</option><option value="walking">Walking</option></select></label><External href={'https://www.google.com/maps/dir/?'+params}>Get directions</External></div><p className="meta">Your starting point is sent to Google Maps only when you open directions. No location tracking. Destination is the venue, not an authorised race-day gate.</p><div className="logistics">{['Event shuttle timetable','Parking allocation / gate assignment','Food, surau and medical-point event map'].map(t=><div key={t}><b>{t}</b><span>Not announced / not verified</span></div>)}</div><p>Confirm access with the circuit. A railway connection does not imply a circuit shuttle.</p><External href={CIRCUIT}>Official circuit information</External></section>;}
function Kit(){const items=['Digital ticket','Rain poncho','Power bank','Sunscreen','Ear protection'];const [packed,setPacked]=useState(()=>{try{const a=JSON.parse(localStorage.getItem('sepang-kit-v2')||'[]');return Array.isArray(a)?a.filter(v=>items.includes(v)):[];}catch{return[];}});const [err,setErr]=useState(false);useEffect(()=>{try{localStorage.setItem('sepang-kit-v2',JSON.stringify(packed));}catch{setErr(true);}},[packed]);return <section><div className="section-head"><h2>Your packing checklist</h2><span>{packed.length} / {items.length} packed</span></div><progress value={packed.length} max={items.length}/><div className="kit">{items.map(x=><label key={x}><input type="checkbox" checked={packed.includes(x)} onChange={()=>setPacked(p=>p.includes(x)?p.filter(v=>v!==x):[...p,x])}/>{x}</label>)}</div><p className="meta">Saved on this device. Check the organiser’s permitted-items policy. {err?'Browser storage unavailable; changes will not survive reload.':''}</p></section>;}
function History(){return <section id="history"><p className="eyeline">Sepang, in context</p><h2>Why Bahrain is racing in Malaysia.</h2><p>The July 2026 announcement describes an agreement between F1, the FIA and both governments to preserve Bahrain’s round amid regional challenges. Malaysia supplies the venue; the race retains Bahrain’s Grand Prix name. The announcement highlighted Sepang’s racing and fans, and included a final-approval caveat.</p><External href={ANNOUNCEMENT}>F1 announcement · 26 July 2026</External><div className="history-list"><article><b>1997–1999</b><h3>A purpose-built venue</h3><p>Construction began in 1997. Hermann Tilke designed the circuit, which opened in 1999.</p></article><article><b>1999</b><h3>Irvine wins the first race</h3><p>Eddie Irvine won the inaugural race. Returning teammate Michael Schumacher supported his title bid.</p></article><article><b>2017</b><h3>Verstappen’s victory</h3><p>Max Verstappen was Sepang’s last F1 winner before the return announced for 2026.</p></article></div><div className="facts"><span><b>5.543 km</b> Circuit length</span><span><b>56</b> Scheduled race laps</span><span><b>1:34.080</b> Vettel’s 2017 lap record</span></div><External href={OFFICIAL}>F1 circuit facts and history</External><h3 className="news-title">Official event news</h3><External href={TICKETS}>Tickets launched for the 2026 event</External><p className="meta">Official-source links checked {VERIFIED}. This is not an auto-updating news feed; open the sources for subsequent announcements.</p></section>;}
function App(){const [now,setNow]=useState(Date.now());useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[]);const next=sessions.find(s=>Date.parse(s.start)>now);const seconds=next?Math.max(0,Math.floor((Date.parse(next.start)-now)/1000)):0;return <><header><a className="brand" href="#top"><strong>SEPANG</strong> RACE HUB</a><nav><a href="#schedule">Weekend</a><a href="#weather">Weather</a><a href="#circuit">Map</a><a href="#history">Story</a></nav></header><main id="top"><div className="intro"><div><p>2–4 OCTOBER 2026 · MALAYSIA</p><h1>Back to Sepang.</h1><p>Formula 1 Gulf Air Bahrain Grand Prix in Malaysia</p></div><div className="countdown"><small>{next?`Until ${next.name}`:'Scheduled weekend elapsed'}</small><strong>{next?`${Math.floor(seconds/86400)}d ${Math.floor(seconds%86400/3600)}h ${Math.floor(seconds%3600/60)}m`:'Check official results'}</strong><span>Clock-based countdown · MYT</span></div></div><Schedule now={now}/><Weather/><section id="circuit"><div className="section-head"><div><p className="eyeline">OpenStreetMap + OpenLayers</p><h2>The actual circuit and surroundings.</h2></div><MapPin/></div><CircuitMap/><p>Use F1’s diagram for numbered corners. Event gates and amenities are not inferred from the map.</p><External href={OFFICIAL}>F1 circuit guide and diagram</External></section><Plan/><Kit/><History/><footer><p>Independent fan companion. Not affiliated with F1 or the organisers.</p><p>Weather: MET Malaysia / data.gov.my. Map: © OpenStreetMap contributors. No simulated live data.</p><External href={CIRCUIT}>Sepang International Circuit</External></footer></main></>;}
createRoot(document.getElementById('root')).render(<App/>);
