import React,{useState} from 'react';
import {exportPlan,saveBlob} from './planExport';
import AIBriefing from './AIBriefing';
import {playSound} from './SoundControl';
import {CalendarPlus,Download} from 'lucide-react';
import useSaved from './useSaved';
import {sessions,timeMY} from './data';

const lists={going:[['ticket','Download my ticket and check the gate'],['route','Plan transport and parking'],['rules','Check the organiser’s bag and entry rules'],['pack','Pack rain cover, sun protection and ear protection'],['charge','Charge my phone and power bank']],online:[['broadcast','Check my local broadcaster and subscription'],['screen','Test my stream or TV setup'],['time','Add the sessions I want to watch'],['friends','Arrange my watch party'],['picks','Save my race prediction']]};
export default function MyWeekend({saveCalendar}){
 const [plan,setPlan,saved]=useSaved('weekend',{mode:'going',done:[],sessions:sessions.map(s=>s.name),notes:''},v=>v&&lists[v.mode]&&Array.isArray(v.done)&&Array.isArray(v.sessions)&&typeof v.notes==='string');
 const [notice,setNotice]=useState(''),[exporting,setExporting]=useState(false);
 const exportAs=async kind=>{setExporting(true);try{await exportPlan(kind,plan,items);playSound('complete');setNotice(kind.toUpperCase()+' downloaded.');}catch{setNotice('Export failed. Try again.');}finally{setExporting(false);}};
 const items=lists[plan.mode],count=items.filter(([id])=>plan.done.includes(id)).length;
 const toggle=(field,id)=>setPlan(p=>({...p,[field]:p[field].includes(id)?p[field].filter(x=>x!==id):[...p[field],id]}));
 const download=()=>{const body=['MY SEPANG WEEKEND','2–4 October 2026 · all times MYT',plan.mode==='going'?'At the circuit':'Watching online','',...sessions.filter(s=>plan.sessions.includes(s.name)).map(s=>new Date(s.start).toLocaleDateString('en-GB',{timeZone:'Asia/Kuala_Lumpur',weekday:'short',day:'numeric',month:'short'})+' · '+timeMY(s.start)+' · '+s.name),'',...items.map(([id,label])=>(plan.done.includes(id)?'[done] ':'[ ] ')+label),'',plan.notes].join('\n');const url=URL.createObjectURL(new Blob([body],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='my-sepang-weekend.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);};
 return <section id="my-weekend" className="weekend-section"><div className="section-heading"><h2>My weekend.</h2><p>{saved?'Your plan saves automatically on this browser.':'Browser saving is unavailable. Download your plan to keep it.'} Download a copy to take with you.</p></div>
  <div className="standings-actions">{[['going','At the circuit'],['online','Watching online']].map(([k,v])=><button key={k} aria-pressed={plan.mode===k} className={plan.mode===k?'active':''} onClick={()=>setPlan(p=>({...p,mode:k}))}>{v}</button>)}</div>
  <div className="weekend-grid"><div><div className="mini-heading"><h3>Before you leave</h3><span>{count} / {items.length} complete</span></div><progress value={count} max={items.length} aria-label="Weekend preparation progress"/>{items.map(([id,label])=><label className="check-row" key={id}><input type="checkbox" checked={plan.done.includes(id)} onChange={()=>toggle('done',id)}/><span>{label}<small>{({ticket:'Before race week · Keep your ticket accessible offline.',route:'Day before · Confirm your route and organiser parking notice.',rules:'Before packing · Avoid a delay at bag checks.',pack:'Before leaving · Prepare for exposed areas and changing weather.',charge:'Night before · Keep tickets, maps and contacts accessible.',broadcast:'Day before · Confirm that your package carries the race.',screen:'Before the session · Check playback and audio.',time:'Now · Calendar reminders prevent missed starts.',friends:'Day before · Share your session plan.',picks:'Before qualifying · Save your picks to compare later.'})[id]}</small></span></label>)}<a className="text-button" href={plan.mode==='going'?'#visit':'https://www.formula1.com/en/information/f1-broadcast-information.45y3LNsT1D6VoK0ZmX8ciJ'} target={plan.mode==='online'?'_blank':undefined} rel="noreferrer">{plan.mode==='going'?'View arrival map ↓':'Find my official broadcaster ↗'}</a></div>
  <div><h3>My sessions</h3>{sessions.map(s=><label className="check-row session-check" key={s.name}><input type="checkbox" checked={plan.sessions.includes(s.name)} onChange={()=>toggle('sessions',s.name)}/><span>{s.name}<small>{new Date(s.start).toLocaleDateString('en-GB',{timeZone:'Asia/Kuala_Lumpur',weekday:'short',day:'numeric',month:'short'})} · {timeMY(s.start)} MYT</small></span></label>)}<button className="outline-action" disabled={!plan.sessions.length} onClick={()=>saveCalendar(sessions.filter(s=>plan.sessions.includes(s.name)))}><CalendarPlus size={18}/>Add selected sessions to calendar</button></div>
  <div><h3>My race-day details</h3>{(plan.mode==='going'?[['seat','Grandstand / seat'],['gate','Ticketed entry gate'],['transport','Transport / parking'],['meetup','Meet-up point'],['leave','My planned departure time']]:[['channel','Broadcaster / stream'],['meetup','Watch party location'],['setup','TV / device']]).map(([key,label])=><label key={key}>{label}<input maxLength={160} value={plan.details?.[key]||''} onChange={e=>setPlan(p=>({...p,details:{...p.details,[key]:e.target.value}}))}/></label>)}<label>My notes<textarea value={plan.notes} maxLength={2000} rows={7} placeholder="Meet-up point, seat, travel plans…" onChange={e=>setPlan(p=>({...p,notes:e.target.value}))}/></label><p className="save-status">Stored on this device only. Clearing browser data removes your plan.</p><div className="plan-exports"><button disabled={exporting} onClick={()=>exportAs('pdf')}>Download PDF</button><button disabled={exporting} onClick={()=>exportAs('image')}>Download image</button><button onClick={download}>Download text</button><button onClick={()=>{saveBlob(new Blob([JSON.stringify({version:1,plan})],{type:'application/json'}),'sepang-plan-backup.json');setNotice('Backup downloaded. Restore it on another device.');}}>Back up plan</button><label className="restore-plan">Restore plan<input type="file" accept="application/json,.json" onChange={async e=>{try{const f=e.target.files[0];if(!f||f.size>40000)throw Error();const j=JSON.parse(await f.text()),v=j.plan;if(j.version!==1||!v||!lists[v.mode]||!Array.isArray(v.done)||!v.done.every(x=>typeof x==='string')||!Array.isArray(v.sessions)||!v.sessions.every(x=>sessions.some(s=>s.name===x))||typeof v.notes!=='string'||v.notes.length>2000||v.details&&(!Object.values(v.details).every(x=>typeof x==='string'&&x.length<=160)))throw Error();setPlan(v);setNotice('Plan restored and saved on this browser.');}catch{setNotice('That file is not a valid Sepang plan backup.');}e.target.value='';}}/></label></div></div></div><p role="status">{notice}</p><p className="save-status">Calendar files include a 30-minute reminder. PDF and image exports are portable copies; backup files can restore your editable plan.</p><AIBriefing topic="plan"/>
 </section>;
}
