import React,{useEffect,useMemo,useRef,useState} from 'react';
import useSaved from './useSaved';
import useAttendance from './useAttendance';
import {checklists} from './checklist';
import {TEAMS} from './teams';
import {TEAM_COLORS} from './standings';
import {sessions,timeMY} from './data';
import {drawCard} from './cardRenderer';
import {saveBlob} from './planExport';
import {playSound} from './SoundControl';
import CardViewer from './CardViewer';
export default function MyWeekend({saveCalendar}){
 const [mode,setMode]=useAttendance();
 const [plan,setPlan,saved]=useSaved('weekend',{mode:'going',done:[],sessions:sessions.map(s=>s.name),notes:''},v=>v&&Array.isArray(v.done)&&Array.isArray(v.sessions)&&typeof v.notes==='string');
 const [details,setDetails]=useSaved('pass-details',{name:'',teamId:'ferrari',channel:'Official broadcaster',meeting:'',shareDetail:false},v=>v&&typeof v.name==='string'&&TEAMS[v.teamId]);
 const [busy,setBusy]=useState(''),[progress,setProgress]=useState(0),[notice,setNotice]=useState(''),[viewer,setViewer]=useState(false),[media,setMedia]=useState(null);
 const canvas=useRef(),abort=useRef();
 const options=checklists[mode],pinned=plan.pinned?.[mode]||options.slice(0,6).map(x=>x[0]);
 const checks=options.filter(x=>pinned.includes(x[0])).map(([id,title])=>({id,title,done:plan.done.includes(mode+':'+id)||mode==='going'&&plan.done.includes(id)}));
 const settings=useMemo(()=>({kind:'pass',mode,name:details.name,teamName:TEAMS[details.teamId].name,teamColor:TEAM_COLORS[details.teamId],checks,sessionText:sessions.filter(s=>plan.sessions.includes(s.name)).map(s=>s.name.replace('Practice ','FP')).join(' · '),detail:details.shareDetail?(mode==='going'?details.meeting:details.channel):''}),[mode,details,plan]);
 useEffect(()=>{const ctx=canvas.current.getContext('2d');let raf,last=0,visible=true;const obs=new IntersectionObserver(([e])=>{visible=e.isIntersecting;});obs.observe(canvas.current);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const draw=now=>{if(visible&&!document.hidden&&now-last>40){drawCard(ctx,settings,reduced?0:now%4000/4000);last=now;}if(!reduced)raf=requestAnimationFrame(draw);};draw(performance.now());return()=>{cancelAnimationFrame(raf);obs.disconnect();};},[settings]);
 useEffect(()=>()=>{abort.current?.abort();},[]);useEffect(()=>()=>{if(media)URL.revokeObjectURL(media.url);},[media]);
 const pin=id=>{if(!pinned.includes(id)&&pinned.length>=6){setNotice('Six essentials per pass. Remove one to make room.');return;}setPlan(p=>({...p,pinned:{...p.pinned,[mode]:pinned.includes(id)?pinned.filter(x=>x!==id):[...pinned,id]}}));setNotice('');};
 const ready=id=>setPlan(p=>({...p,done:(p.done.includes(mode+':'+id)||mode==='going'&&p.done.includes(id))?p.done.filter(x=>x!==mode+':'+id&&x!==id):[...p.done,mode+':'+id]}));
 const download=async kind=>{setBusy(kind);setNotice('');setProgress(0);try{let blob,ext=kind;
 if(kind==='gif'||kind==='video'){abort.current=new AbortController();const fn=kind==='gif'?(await import('./exportGif')).exportGif:(await import('./exportVideo')).exportVideo;blob=await fn(settings,null,setProgress,abort.current.signal);ext=kind==='gif'?'gif':blob.type.includes('mp4')?'mp4':'webm';}
 else{const c=document.createElement('canvas');c.width=1080;c.height=1350;drawCard(c.getContext('2d'),settings,0);if(kind==='pdf'){const {jsPDF}=await import('jspdf');const pdf=new jsPDF({unit:'px',format:[1080,1350]});pdf.addImage(c.toDataURL('image/png'),'PNG',0,0,1080,1350);pdf.save('sepang-season-pass.pdf');}else blob=await new Promise(r=>c.toBlob(r,'image/png'));}
 if(blob){saveBlob(blob,`sepang-season-pass-${mode}.${ext}`);if(kind==='gif'||kind==='video'){setMedia({url:URL.createObjectURL(blob),type:blob.type});setViewer(true);}}playSound('complete');setNotice('Your pass is downloaded.');
 }catch(e){setNotice(e.name==='AbortError'?'Export cancelled. Your pass is saved.':'Could not export. Please try PNG.');}finally{setBusy('');abort.current=null;}};
 return <section id="my-weekend" className="weekend-section season-studio"><div className="section-heading"><div><span className="eyebrow">PACK THE VIBE. PLAN THE WEEKEND.</span><h2>My weekend pass.</h2></div><p>Six essentials. Your sessions. One pass worth sharing.</p></div><div className="pass-layout"><div className="pass-editor"><div className="attendance-toggle" aria-label="Weekend attendance">{[['going','At the circuit'],['online','Watching online']].map(([key,label])=><button aria-pressed={mode===key} key={key} onClick={()=>setMode(key)}>{label}</button>)}</div><p className="micro-copy">This choice also updates your fan collectible.</p>
 <div className="compact-fields"><label>Pass holder<input maxLength={40} placeholder="Your name or nickname" value={details.name} onChange={e=>setDetails(d=>({...d,name:e.target.value}))}/></label><label>Team<select value={details.teamId} onChange={e=>setDetails(d=>({...d,teamId:e.target.value}))}>{Object.entries(TEAMS).map(([k,t])=><option key={k} value={k}>{t.name}</option>)}</select></label>{mode==='online'?<label>Watching with<select value={details.channel} onChange={e=>setDetails(d=>({...d,channel:e.target.value}))}><option>Official broadcaster</option><option>My licensed streaming service</option><option>Friends / watch party</option><option>Race highlights later</option></select></label>:<label>Meet-up spot <small>optional</small><input maxLength={90} value={details.meeting} placeholder="Agree a spot with your friends" onChange={e=>setDetails(d=>({...d,meeting:e.target.value}))}/></label>}</div>
 <label className="inline-check"><input type="checkbox" checked={!!details.shareDetail} onChange={e=>setDetails(d=>({...d,shareDetail:e.target.checked}))}/>Show meet-up / viewing detail on shared pass</label><a className="useful-link" href={mode==='going'?'#visit':'https://www.formula1.com/en/information/f1-broadcast-information.45y3LNsT1D6VoK0ZmX8ciJ'} target={mode==='online'?'_blank':undefined} rel="noreferrer">{mode==='going'?'Open circuit directions ↗':'Find official broadcasters & streaming ↗'}</a>
 <div className="checklist-heading"><h3>Build your six.</h3><span>{pinned.length}/6 selected · {checks.filter(x=>x.done).length} ready</span></div><div className="fun-checklist">{options.map(([id,title,desc,icon])=><article key={id} className={pinned.includes(id)?'picked':''}><label><input type="checkbox" checked={pinned.includes(id)} onChange={()=>pin(id)} disabled={!pinned.includes(id)&&pinned.length===6}/><span className="check-icon" aria-hidden="true">{icon}</span><span><strong>{title}</strong><small>{desc}</small></span></label>{pinned.includes(id)&&<label className="ready-check"><input type="checkbox" checked={checks.find(c=>c.id===id)?.done||false} onChange={()=>ready(id)}/>Ready ✓</label>}</article>)}</div>
 <h3>Your sessions</h3><div className="session-pills">{sessions.map(s=><button key={s.name} aria-pressed={plan.sessions.includes(s.name)} onClick={()=>setPlan(p=>({...p,sessions:p.sessions.includes(s.name)?p.sessions.filter(x=>x!==s.name):[...p.sessions,s.name]}))}>{s.name}<small>{new Date(s.start).toLocaleDateString('en-GB',{timeZone:'Asia/Kuala_Lumpur',weekday:'short'})} · {timeMY(s.start)}</small></button>)}</div><button className="outline-action" disabled={!plan.sessions.length} onClick={()=>saveCalendar(sessions.filter(s=>plan.sessions.includes(s.name)))}>Add my sessions to calendar</button><small className="micro-copy">30-minute reminders · all times MYT</small>
 </div><div className="season-preview"><button className="canvas-button" aria-label="Open my season pass" onClick={()=>{setMedia(null);setViewer(true);}}><canvas ref={canvas} width="648" height="810"/></button><p className="micro-copy">Live preview · tap to hold your pass</p><div className="pass-downloads">{['png','gif','video','pdf'].map(k=><button key={k} disabled={!!busy} onClick={()=>download(k)} title={k==='video'?'Four-second MP4 movie of this entire pass. Use GIF if your browser cannot encode MP4.':k==='gif'?'Four-second animated loop, ready to share.':k==='pdf'?'A printable copy of this exact pass.':'Full-resolution image for WhatsApp and social sharing.'}>{busy===k?`${progress}%`:k==='video'?'Video':k.toUpperCase()}</button>)}</div>{busy&&<button onClick={()=>abort.current?.abort()} disabled={!abort.current}>Cancel export</button>}<p role="status">{notice}</p><small className="micro-copy">{saved?'Saved on this browser.':'Storage unavailable; download to keep your pass.'} Fan souvenir, not an admission ticket.</small></div></div>{viewer&&<CardViewer settings={settings} media={media} onClose={()=>setViewer(false)}/>}</section>;
}
