import React from 'react';
import {CalendarPlus,Download} from 'lucide-react';
import useSaved from './useSaved';
import {sessions,timeMY} from './data';

const lists={going:[['ticket','Download my ticket and check the gate'],['route','Plan transport and parking'],['rules','Check the organiser’s bag and entry rules'],['pack','Pack rain cover, sun protection and ear protection'],['charge','Charge my phone and power bank']],online:[['broadcast','Check my local broadcaster and subscription'],['screen','Test my stream or TV setup'],['time','Add the sessions I want to watch'],['friends','Arrange my watch party'],['picks','Save my race prediction']]};
export default function MyWeekend({saveCalendar}){
 const [plan,setPlan,saved]=useSaved('weekend',{mode:'going',done:[],sessions:sessions.map(s=>s.name),notes:''},v=>v&&lists[v.mode]&&Array.isArray(v.done)&&Array.isArray(v.sessions)&&typeof v.notes==='string');
 const items=lists[plan.mode],count=items.filter(([id])=>plan.done.includes(id)).length;
 const toggle=(field,id)=>setPlan(p=>({...p,[field]:p[field].includes(id)?p[field].filter(x=>x!==id):[...p[field],id]}));
 const download=()=>{const body=['MY SEPANG WEEKEND','2–4 October 2026 · all times MYT',plan.mode==='going'?'At the circuit':'Watching online','',...sessions.filter(s=>plan.sessions.includes(s.name)).map(s=>new Date(s.start).toLocaleDateString('en-GB',{timeZone:'Asia/Kuala_Lumpur',weekday:'short',day:'numeric',month:'short'})+' · '+timeMY(s.start)+' · '+s.name),'',...items.map(([id,label])=>(plan.done.includes(id)?'[done] ':'[ ] ')+label),'',plan.notes].join('\n');const url=URL.createObjectURL(new Blob([body],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='my-sepang-weekend.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);};
 return <section id="my-weekend" className="weekend-section"><div className="section-heading"><h2>My weekend.</h2><p>{saved?'Your plan saves automatically on this browser.':'Browser saving is unavailable. Download your plan to keep it.'} Download a copy to take with you.</p></div>
  <div className="standings-actions">{[['going','At the circuit'],['online','Watching online']].map(([k,v])=><button key={k} aria-pressed={plan.mode===k} className={plan.mode===k?'active':''} onClick={()=>setPlan(p=>({...p,mode:k}))}>{v}</button>)}</div>
  <div className="weekend-grid"><div><div className="mini-heading"><h3>Get ready</h3><span>{count} / {items.length} complete</span></div><progress value={count} max={items.length} aria-label="Weekend preparation progress"/>{items.map(([id,label])=><label className="check-row" key={id}><input type="checkbox" checked={plan.done.includes(id)} onChange={()=>toggle('done',id)}/><span>{label}</span></label>)}<a className="text-button" href={plan.mode==='going'?'#visit':'https://www.formula1.com/en/information/f1-broadcast-information.45y3LNsT1D6VoK0ZmX8ciJ'} target={plan.mode==='online'?'_blank':undefined} rel="noreferrer">{plan.mode==='going'?'View arrival map ↓':'Find my official broadcaster ↗'}</a></div>
  <div><h3>My sessions</h3>{sessions.map(s=><label className="check-row session-check" key={s.name}><input type="checkbox" checked={plan.sessions.includes(s.name)} onChange={()=>toggle('sessions',s.name)}/><span>{s.name}<small>{new Date(s.start).toLocaleDateString('en-GB',{timeZone:'Asia/Kuala_Lumpur',weekday:'short',day:'numeric',month:'short'})} · {timeMY(s.start)} MYT</small></span></label>)}<button className="outline-action" disabled={!plan.sessions.length} onClick={()=>saveCalendar(sessions.filter(s=>plan.sessions.includes(s.name)))}><CalendarPlus size={18}/>Add selected sessions to calendar</button></div>
  <div><label>My notes<textarea value={plan.notes} maxLength={2000} rows={7} placeholder="Meet-up point, seat, travel plans…" onChange={e=>setPlan(p=>({...p,notes:e.target.value}))}/></label><p className="save-status">Stored on this device only. Clearing browser data removes your plan.</p><button className="outline-action" onClick={download}><Download size={18}/>Download my plan</button></div></div>
 </section>;
}
