import GlassSurface from './GlassSurface';
import {SlidersHorizontal,Volume2,Music2,X} from 'lucide-react';
import React,{useEffect,useRef,useState} from 'react';
import LiquidGlass from 'liquid-glass-react';
import {createUISFX} from 'uisfx';
const read=(k,f)=>{try{return localStorage.getItem('sepang26:'+k)??f;}catch{return f;}};
const save=(k,v)=>{try{localStorage.setItem('sepang26:'+k,v);}catch{}};
let ui;
function player(){if(!ui)ui=createUISFX({pack:'zen',volume:Number(read('volume','.65'))});return ui;}
export function playSound(cue){try{if(read('sound','off')==='on'&&read('sfx','on')==='on')player().unlock().then(()=>ui.play(cue)).catch(()=>{});}catch{}}
export default function SoundControl(){
 const [enabled,setEnabled]=useState(()=>read('sound','off')==='on'),[sfx,setSfx]=useState(()=>read('sfx','on')==='on'),[music,setMusic]=useState(()=>read('music','off')==='on'),[volume,setVolume]=useState(()=>Number(read('volume','.65'))),[musicVolume,setMusicVolume]=useState(()=>Number(read('music-volume','.10'))),[notice,setNotice]=useState('');const audio=useRef(null),menu=useRef(null);
 useEffect(()=>{const close=e=>{if(menu.current?.open&&!e.target.closest('.sound-controls'))menu.current.open=false;};const key=e=>{if(e.key==='Escape'&&menu.current)menu.current.open=false;};document.addEventListener('pointerdown',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',key);};},[]);
 const startMusic=()=>{if(!audio.current)return;audio.current.volume=musicVolume;audio.current.play().then(()=>setNotice('')).catch(()=>setNotice('Tap Resume music to start playback.'));};
 useEffect(()=>{if(!enabled||!music)audio.current?.pause();},[enabled,music]);
 useEffect(()=>{let last=0;const click=e=>{if(enabled&&music&&audio.current?.paused&&!e.target.closest('.sound-controls'))startMusic();const el=e.target.closest('button,a,summary,input[type="checkbox"]');if(!el||el.disabled||el.closest('.sound-controls')||Date.now()-last<100)return;last=Date.now();playSound(el.tagName==='SUMMARY'?'expand':el.type==='checkbox'?(el.checked?'check':'uncheck'):'select');};document.addEventListener('click',click);return()=>document.removeEventListener('click',click);},[enabled,music,musicVolume]);
 const enable=next=>{setEnabled(next);save('sound',next?'on':'off');if(next){playSound('toggle-on');if(music)startMusic();}else{ui?.stopAll();audio.current?.pause();}};
 return <div className="sound-controls"><audio ref={audio} src="/paddock-pulse.mp3" loop preload="none" aria-label="Paddock Pulse background music" onError={()=>setNotice('Music could not load. Please try again.')}/><div className="zen-glass"><LiquidGlass displacementScale={24} elasticity={.18} blurAmount={.15} cornerRadius={30} padding="0px" style={{position:'absolute',top:'50%',left:'50%'}}><button className="sound-control" aria-pressed={enabled} onClick={()=>enable(!enabled)}>Sound {enabled?'on':'off'}</button></LiquidGlass></div><details ref={menu}><summary aria-label="Sound settings"><SlidersHorizontal size={19}/></summary><GlassSurface className="sound-popover"><div className="sound-heading"><div><small>SET THE MOOD</small><strong>Sound & music</strong></div><button className="icon-button" aria-label="Close sound settings" onClick={()=>menu.current.open=false}><X size={18}/></button></div><label className="audio-toggle"><span><Volume2 size={18}/><span>Master sound<small>Mute everything in one tap</small></span></span><input type="checkbox" role="switch" checked={enabled} onChange={e=>enable(e.target.checked)}/></label><div className="audio-group"><label className="audio-toggle"><span>Zen effects</span><input type="checkbox" role="switch" checked={sfx} onChange={e=>{setSfx(e.target.checked);save('sfx',e.target.checked?'on':'off');if(e.target.checked)playSound('select');else ui?.stopAll();}}/></label><label className="audio-volume"><span>Effects volume <output>{Math.round(volume*100)}%</output></span><input aria-label="Zen volume" type="range" min="0" max="1" step=".05" value={volume} onChange={e=>{const v=+e.target.value;setVolume(v);save('volume',v);player().setVolume(v);}}/></label></div><div className="audio-group"><label className="audio-toggle"><span><Music2 size={18}/><span>Paddock Pulse<small>Background music · looping</small></span></span><input type="checkbox" role="switch" checked={music} onChange={e=>{const on=e.target.checked;setMusic(on);save('music',on?'on':'off');if(on){enable(true);startMusic();}else audio.current?.pause();}}/></label><label className="audio-volume"><span>Music volume <output>{Math.round(musicVolume*100)}%</output></span><input aria-label="Music volume" type="range" min="0" max=".5" step=".01" value={musicVolume} onChange={e=>{const v=+e.target.value;setMusicVolume(v);save('music-volume',v);if(audio.current)audio.current.volume=v;}}/></label></div><button className="audio-preview" onClick={()=>{save('sfx','on');setSfx(true);enable(true);playSound('success');}}><Volume2 size={16}/>Preview Zen sound</button>{notice&&<><p role="status">{notice}</p><button onClick={()=>{enable(true);startMusic();}}>Resume music</button></>}</GlassSurface></details></div>;
}
